# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-10 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='name',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='role_type',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.RoleType'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='status',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Status'),
        ),
        migrations.AlterField(
            model_name='roletype',
            name='role_type',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
