# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-11 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200210_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='roletype',
            name='code',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='code',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
